name: Continuous Integration - Fuzz Testing

on:
  push:
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:

      # Checkout latest repo code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup python with correct version
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      # Install python dependencies
      - name: Install PIP dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run fuzzing
      - name: Fuzz Testing
        run: |
          python -m test.fuzz.main