name: Continuous Integration - Fuzz Testing

on:
  push:
  pull_request:

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:

      # Checkout latest repo code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup python with correct version (3.13.5 for this project)
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      # Install python dependencies (see requirements.txt for full list)
      - name: Install PIP dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run fuzzing in project directory
      - name: Fuzz Execution
        run: |
          python -m test.fuzz.fuzz

      # Upload fuzzing summary to GitHub Actions summary (the fuzzing pipeline gens fuzzingsummary.md)
      - name: Fuzz Summary
        run: |
          echo "## Fuzzing Summary" >> $GITHUB_STEP_SUMMARY
          cat fuzzingsummary.md >> $GITHUB_STEP_SUMMARY