name: Continuous Integration - Unit Testing

on:
  push:
  pull_request:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:

      # Checkout latest repo code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup python with correct version
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      # Install python dependencies
      - name: Install PIP dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Unit Testing
        env:
          REPORT_OUTPUT: md_report.md
        run: |
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"
          echo "REPORT_FILE=${REPORT_OUTPUT}" >> "$GITHUB_ENV"
          pytest -v --md-report --md-report-flavor gfm --md-report-output "$REPORT_OUTPUT"

      - name: Add Unit Testing Summary to GitHub Summary
        shell: bash
        run: |
          if [ -f "$REPORT_FILE" ]; then
            echo "<details><summary>Unit Test Report</summary>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat "$REPORT_FILE" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "</details>" >> $GITHUB_STEP_SUMMARY
          fi

      # Upload report as artifact
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ${{ env.REPORT_FILE }}