name: Continuous Integration - Unit Testing

on:
  push:
  pull_request:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:

      # Checkout latest repo code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup python with correct version
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      # Install python dependencies
      - name: Install PIP dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Unit Testing
        run: |
          python -m test.unit.unit

      # Upload unit testing summary to GitHub Actions summary
      - name: Unit Testing Summary
        run: |
          echo "## Unit Testing Summary" >> $GITHUB_STEP_SUMMARY
          cat unittestsummary.md >> $GITHUB_STEP_SUMMARY