name: Continuous Integration - Unit Testing

on:
  push:
  pull_request:

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:

      # Checkout latest repo code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup python with correct version
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.5"

      # Install python dependencies
      - name: Install PIP dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Unit Testing
        env:
          REPORT_OUTPUT: md_report.md
        run: |
          echo "REPORT_FILE=${REPORT_OUTPUT}" >> "$GITHUB_ENV"
          export PYTHONPATH="${PYTHONPATH}:${GITHUB_WORKSPACE}"
          pytest -s --md-report --md-report-flavor gfm --md-report-color off --md-report-output "$REPORT_OUTPUT"

      # Add unit test report to GitHub Summary
      - name: Add Unit Testing Summary to GitHub Summary
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const content = fs.readFileSync(process.env.REPORT_FILE, 'utf8');
            await core.summary
              .addHeading('Unit Test Report')
              .addRaw(content)
              .write();

      # Upload report as artifact
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: ${{ env.REPORT_FILE }}